name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: install cmake
      run: sudo apt-get install cmake
    
    - name: install gtest
      run: sudo apt-get install libgtest-dev
      
    - uses: actions/checkout@v2
    
    - name: compile test
      run: make compile_test
      
    - name: run test
      run: make run_test
